# Generated by Django 5.2.7 on 2025-10-13 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=300, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Для карточки на главной",
                        max_length=500,
                        verbose_name="Краткое описание",
                    ),
                ),
                ("content", models.TextField(verbose_name="Полный текст статьи")),
                (
                    "image",
                    models.ImageField(
                        upload_to="articles/", verbose_name="Изображение"
                    ),
                ),
                ("published_date", models.DateField(verbose_name="Дата публикации")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликована"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Просмотры")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="ПРАВОЗАЩИТНИК",
                        max_length=200,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(blank=True, max_length=300, verbose_name="Слоган"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Для секции 'О компании'",
                        verbose_name="Описание компании",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="Адрес"),
                ),
                ("vk_link", models.URLField(blank=True, verbose_name="Ссылка на VK")),
                (
                    "telegram_link",
                    models.URLField(blank=True, verbose_name="Ссылка на Telegram"),
                ),
                (
                    "whatsapp_link",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="WhatsApp (номер)"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SEO заголовок"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="SEO описание"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Информация о компании",
                "verbose_name_plural": "Информация о компании",
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Подзаголовок"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Записаться на консультацию",
                        max_length=100,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "button_link",
                    models.CharField(
                        default="#contact",
                        help_text="Например: #contact или /services/",
                        max_length=200,
                        verbose_name="Ссылка кнопки",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        upload_to="hero/", verbose_name="Фоновое изображение"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Слайд баннера",
                "verbose_name_plural": "Слайды баннера",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="Имя клиента"),
                ),
                (
                    "client_company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Компания клиента"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/",
                        verbose_name="Фото клиента",
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True,
                        help_text="Например: 'Январь 2024'",
                        max_length=100,
                        verbose_name="Дата отзыва (текст)",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["order", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL slug"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Эмодзи или иконка для карточки",
                        max_length=50,
                        verbose_name="Иконка/Эмодзи",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Для карточки на главной",
                        max_length=300,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Полное описание"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LawyerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "position",
                    models.CharField(max_length=200, verbose_name="Должность"),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Отображается при наведении на карточку",
                        verbose_name="Биография",
                    ),
                ),
                (
                    "experience_text",
                    models.CharField(
                        blank=True,
                        help_text="Например: '12 лет юридической практики'",
                        max_length=200,
                        verbose_name="Текст об опыте",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="lawyers/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "specialization",
                    models.ManyToManyField(
                        blank=True,
                        related_name="lawyers",
                        to="lawyer.service",
                        verbose_name="Специализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Юрист",
                "verbose_name_plural": "Юристы",
                "ordering": ["order", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("completed", "Завершена"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="lawyer.service",
                        verbose_name="Выбранная услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на консультацию",
                "verbose_name_plural": "Заявки на консультацию",
                "ordering": ["-created"],
            },
        ),
    ]
